#!/bin/sh

rmenu="$(: | dmenu -p "Rmenu" | xargs -I '{}' R --quiet -e {} | grep -vE '^>' | tr -s " " | cut -d " " -f 2-)"

if [ "$rmenu" != "" ]; then
    if [ "$1" = "--copy" -o "$1" = "-c" ]; then
	echo $rmenu | dmenu
	echo $rmenu | xclip -r -i -selection clipboard
    else
	echo $rmenu | dmenu
    fi
fi
